import sys, os, time, json

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, ROOT)

import time
import json

from src.engine.strategy_engine import StrategyEngine
from src.core.portfolio.manager import PortfolioManager
from src.core.strategy.base import BaseStrategy
from src.core.strategy.performance import PerformanceEngine
from src.core.strategy.context import StrategyContext


# ============================================================
#  MOCKS
# ============================================================
class MockAPI:
    """Dummy API; real Shoonya API not needed for this test."""
    pass


class MockOrderManager:
    """Simulates real order placement + fill callbacks."""
    def __init__(self):
        self.orders = []
        self.fills = []

    def place_order(self, **kwargs):
        print(f"[MockOrderManager] ORDER PLACED: {kwargs}")
        self.orders.append(kwargs)
        order_id = len(self.orders)
        return {"order_id": order_id}

    def simulate_fill(self, strategy_name, side, price, qty):
        fill = {
            "strategy_name": strategy_name,
            "transaction_type": side,  # 'B' or 'S'
            "price": price,
            "filled_qty": qty,
        }
        print(f"[MockOrderManager] FILL GENERATED: {fill}")
        self.fills.append(fill)
        return fill


class MockWebSocket:
    """Simulates incoming ticks calling engine.on_tick()."""
    def __init__(self, on_tick_callback):
        self.on_tick_callback = on_tick_callback

    def emit(self, tick):
        print(f"[MockWebSocket] TICK: {tick}")
        self.on_tick_callback(tick)


# ============================================================
#  STRATEGY UNDER TEST
# ============================================================
class SmokeStrategy(BaseStrategy):
    """
    A very small strategy that:
      - Buys at lp=103
      - Sells at lp=108
    """
    def __init__(self):
        super().__init__(
            name="smoke_strat",
            symbol="TEST",
            params={"dummy": True},
            window_size=5
        )
        self.events = []
        # initialize performance engine
        self.ctx.performance = PerformanceEngine(starting_equity=100000.0)

    def on_start(self, api, order_manager):
        print("[SmokeStrategy] on_start")
        self.events.append("start")

    def on_tick(self, api, order_manager, tick, ctx: StrategyContext):
        price = tick["lp"]
        ctx.append_tick(tick)
        ctx.update_unrealized(price)

        self.events.append(("tick", price))
        print(f"[SmokeStrategy] TICK RECEIVED: {price}")

        if price == 103:
            print("[SmokeStrategy] → BUY signal")
            self.place_limit(order_manager, side="B", price=103, qty=1)

        if price == 108:
            print("[SmokeStrategy] → SELL signal")
            self.place_limit(order_manager, side="S", price=108, qty=1)

    def on_stop(self, api, order_manager):
        print("[SmokeStrategy] on_stop")
        self.events.append("stop")


# ============================================================
#  SMOKE TEST
# ============================================================
def run_smoke_test():
    print("\n============================")
    print("  FULL END-TO-END SMOKE TEST")
    print("============================\n")

    api = MockAPI()
    om = MockOrderManager()

    # Strategy engine with worker threads enabled
    engine = StrategyEngine(api, om, max_workers=2, queue_size=100)

    # Portfolio manager
    portfolio = PortfolioManager(starting_equity=100000.0)
    engine.portfolio = portfolio

    # Strategy setup
    strat = SmokeStrategy()
    engine.register(strat)
    portfolio.add_strategy(strat)

    # Mock WebSocket feed
    ws = MockWebSocket(engine.on_tick)

    # Start the engine
    engine.start()

    # Emit price ticks (simulates a live feed)
    ticks = [
        {"lp": 101},
        {"lp": 102},
        {"lp": 103},  # BUY
        {"lp": 105},
        {"lp": 108},  # SELL
        {"lp": 110},
    ]

    for t in ticks:
        ws.emit(t)
        time.sleep(0.05)

    # Simulate fills generated by the exchange/broker
    buy_fill = om.simulate_fill("smoke_strat", "B", price=103, qty=1)
    engine.on_order_update(buy_fill)

    sell_fill = om.simulate_fill("smoke_strat", "S", price=108, qty=1)
    engine.on_order_update(sell_fill)

    # let the engine catch up
    time.sleep(0.3)

    # Stop the engine
    engine.stop()

    # ============================================================
    #  REPORTING
    # ============================================================
    print("\n--- STRATEGY EVENTS ---")
    print(strat.events)

    print("\n--- POSITION STATE ---")
    print("Qty:", strat.ctx.position.qty)
    print("AvgPrice:", strat.ctx.position.avg_price)

    print("\n--- PNL SNAPSHOT ---")
    print(strat.ctx.pnl.snapshot())

    print("\n--- PORTFOLIO SNAPSHOT ---")
    print(json.dumps(portfolio.snapshot(), indent=2))

    print("\n--- PERFORMANCE REPORT ---")
    print(json.dumps(strat.ctx.performance_report(), indent=2, default=str))

    print("\n🎉 SMOKE TEST COMPLETED SUCCESSFULLY!\n")


# PyTest identifier
def test_smoke():
    run_smoke_test()



# Entry point
if __name__ == "__main__":
    run_smoke_test()
